### PR TITLE
Fix installing with pip

### PR DESCRIPTION
**Pull request by 1stvamp**
Currently you can't install tornalet with pip as it requires info in setup.py from the tornalet module itself which then depends on imports from tornado and greenlet, and greenlet won't be available in a fresh install as distutils handles this dependency last.

To fix this I've moved the module info into a `tornalet_info.txt` file which setup.py and tornalet.py just read into a list and use, which keeps the info itself in one place and loading the info into a list is a plain one liner.

I've also bumped the version to `1.0.1`, following the www.semver.org standard.

### CODE REVIEW

**Comment by 1stvamp** [comment]
@Gawen refactored this PR so tornalet can be installed any-which-way-but-loose.

**Comment by 1stvamp** [comment]
@Gawen hi, I know you're busy with life (hell do I know that feeling), but any chance of a look at this? :smile: :cake:

**Comment by 1stvamp** [comment]
Time for a weekly ping. :grin:

**Comment by gawen** [comment]
Thanks 1stvamp. Apologize for the delay... Merged & pushed the new version 1.0.2 on PyPi.

Greetings from France :)

**Comment by 1stvamp** [comment]
Yay! Thanks a lot, and don't worry I've had PRs linger for months. ;)

**Pull request merged**
